return {
  'christoomey/vim-tmux-navigator',
  'github/copilot.vim',
  'haishanh/night-owl.vim',
  'jlcrochet/vim-rbs',
  'lifepillar/vim-solarized8',
  'machakann/vim-highlightedyank',
  'nvim-lua/plenary.nvim',
  'nvim-lua/popup.nvim',
  'slim-template/vim-slim',
  'tpope/vim-bundler',
  'tpope/vim-dispatch',
  'tpope/vim-obsession',
  'tpope/vim-rails',
  'tpope/vim-repeat',
  'tpope/vim-rhubarb',
}
