# Small program to send battery notifications.
# https://github.com/doums/bato

# tick_rate: u32, default: 5
#
# The refresh rate in second of bato.
#
tick_rate: 1

# bat_name: String, default: BAT0
#
# The battery name under /sys/class/power_supply/
#
bat_name: BAT0

# critical_level: String, required
#
# The critical level of the battery, as a percentage.
#
critical_level: 5

# low_level: String, required
#
# The low level of the battery, as a percentage.
#
low_level: 30

# full_design: bool, default: true
#
# Whether or not the current level is calculated based on the full design value.
#
full_design: true

# # # # # # # # #
# notifications #
# # # # # # # # #

critical:
  summary: Critical battery level!
  body: Plug the power cable asap!
  icon: battery-caution
low:
  summary: Battery low
  icon: battery-040
full:
  summary: Battery full
  icon: battery-full
  urgency: Low
charging:
  summary: Battery
  body: Charging
  icon: battery-good-charging
discharging:
  summary: Battery
  body: Discharging
  icon: battery-good

